import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '@/src/styles/globals.css';

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  preload: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className + ' bg-cf-dark text-white'}>{children}</body>
    </html>
  );
}
